[project]
authors = ["Dan Allan <>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "database-benchmark"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
pymongo = ">=4.11,<5"
adbc-driver-manager = ">=1.3.0,<2"
adbc-driver-postgresql = ">=1.3.0,<2"
pyarrow = ">=19.0.0,<20"
numpy = ">=2.2.2,<3"
pandas = ">=2.2.3,<3"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.3.5,<5"
toolz = ">=1.0.0,<2"
