version: '3'

services:
  mongodb:
    image: docker.io/library/mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    tmpfs:
      - /data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  postgres:
    image: docker.io/library/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    tmpfs:
      - /var/lib/postgresql/data
      - /dev/shm/pg_wal
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  mongodb_data:
  postgres_data:
